name: Checkmarx One Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '00 7 * * *' # Every day at 07:00

jobs:
  cx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@9fda5a4a2c297608117a5a56af424502a9192e57 # v.2.0.34
        with:
          base_uri: https://eu.ast.checkmarx.net/
          cx_tenant: ast_abdul_ansari
          cx_client_id: Test0207
          cx_client_secret: 3izhMbthdZQfxMlOyLT0xKkfBrKpm6Sq
          additional_params: --tags phoenix --threshold "sast-critical=1;sast-high=1;sast-medium=1;sast-low=1;sca-critical=1;sca-high=1;sca-medium=1;sca-low=1;iac-security-critical=1;iac-security-high=1;iac-security-medium=1;iac-security-low=1;"
